# Семинар 2

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [35]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(vec)

numpy.ndarray

In [10]:
dir(pyvec)
pyvec * 2

[[1, 2], [3, 4], [5, 6], [1, 2], [3, 4], [5, 6]]

In [23]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [20]:
vec @ vec.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [7]:
pyvec = [[1, 2], [3, 4], [5, 6]]
print(type(pyvec))
pyvec

<class 'list'>


[[1, 2], [3, 4], [5, 6]]

In [22]:
vec[::-2][1]

array([1, 2])

In [25]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [36]:
vec.dtype

dtype('int32')

In [28]:
type(vec)

numpy.ndarray

Размер массива:

In [29]:
vec.shape

(3, 2)

Число осей:

In [30]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [37]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
np.sum(vec)

21

In [39]:
np.sum(vec, axis=0)

array([ 9, 12])

In [40]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [41]:
vec.sum()

21

Транспонируем массив:

In [42]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [47]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [44]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [50]:
temp = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
temp.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
vec.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Индексирование:

In [51]:
vec[1:10:2, 1]

array([4])

In [ ]:
vec[:, :]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
vec[1:2, 0]

array([3])

In [ ]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
vec[::-2, 1]

array([6, 2])

Булевы массивы:

In [54]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
is_even = (vec % 2 == 0)
print(is_even)
type(is_even)

[[False  True]
 [False  True]
 [False  True]]


numpy.ndarray

In [ ]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [55]:
vec[is_even == True]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [56]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [57]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [58]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
np.hstack((vec, np.zeros((3, 5))))

array([[1., 2., 0., 0., 0., 0., 0.],
       [3., 4., 0., 0., 0., 0., 0.],
       [5., 6., 0., 0., 0., 0., 0.]])

In [62]:
np.vstack((vec, np.zeros((7, 2))))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [ ]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [ ]:
vec ** 3

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [65]:
vec * np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [66]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [70]:
vec.dot(vec)

ValueError: ignored

In [69]:
vec.dot(vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [71]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [72]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [73]:
np.ones((2,))

array([1., 1.])

In [74]:
np.zeros((2, 2)) * np.ones((2,))

array([[0., 0.],
       [0., 0.]])

In [75]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
np.arange(3).reshape(3, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [ ]:
np.random.rand(2, 3)

array([[0.00422451, 0.39796618, 0.17185922],
       [0.96079367, 0.529853  , 0.30382593]])

In [ ]:
np.random.seed(2018)
np.random.rand(2, 3)

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539]])

In [ ]:
np.random.seed(2018)
np.random.rand(2, 3)

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539]])

In [ ]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [ ]:
np.random.normal(2, 1, size=3)

array([2.50227689, 2.8560293 , 1.85720992])

In [ ]:
np.random.randint(5, 10, size=3)

array([6, 5, 7])

Почему вообще используют `numpy`?

In [78]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [79]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

Wall time: 12.4 s


In [80]:
%%time
C = A @ B

Wall time: 3.98 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐